x = [7 8 9 13 15];
y = fliplr(x);
z = conv(x,y);
disp(z);
subplot(3,1,1);
stem(x);
xlabel('time');
ylabel('amplitude');
title('input x');
subplot(3,1,2);
stem(y);
xlabel('time');
ylabel('amplitude');
title('input y');
subplot(3,1,3);
stem(z);
xlabel('time');
ylabel('amplitude');
title('correlation');